version: '3.7'
services:
  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    networks: 
        - wordpress-db
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks: 
        - wordpress-db
  seleniumhub:
      image: selenium/standalone-firefox-debug:latest
      ports:
        - 4444:4444
        - 5900:5900
      networks: 
        - wordpress-db
  test:
       image: uscdev/selenium-test
       networks:
           - wordpress-db
       depends_on:
           - seleniumhub 
           - wordpress
networks:
  wordpress-db:
    driver: overlay
